spring:
  datasource:
    url: jdbc:mysql://localhost:3306/class_report?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: murasame521
    driver-class-name: com.mysql.cj.jdbc.Driver



logging:
  level:
    com.xuegongbu: debug
