server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: class-report-system
  
  datasource:
    url: jdbc:mysql://localhost:3306/class_report?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: murasame521
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xuegongbu.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

jwt:
  secret: class-report-system-jwt-secret-key-for-token-generation-2025
  expiration: 86400000



logging:
  level:
    com.xuegongbu: debug
